### ISSUE TITLE
Fix error with FlagIcon during yarn test execution

### ISSUE THREAD

**Issue by fabasoad** [fabasoad/business-card#24]
### Link
[Build #74](https://pipelines.actions.githubusercontent.com/kTIyfjs5dhZwnPgVNRUdVbfWDp7M9dt0knrNFoKO2tMcSl47sd/_apis/pipelines/1/runs/74/signedlogcontent/3?urlExpires=2020-05-04T01%3A16%3A36.1698234Z&urlSigningMethod=HMACV1&urlSignature=zQ9R3O%2F1zMzjoKqxtrh4S0Y%2FqqJFoEbtEMl7BQOKAzE%3D)
### Details
```console
2020-05-04T01:14:32.2378903Z   â— Console
2020-05-04T01:14:32.2379284Z 
2020-05-04T01:14:32.2379922Z     console.error
2020-05-04T01:14:32.2382927Z       Warning: Failed prop type: Invalid prop `code` of value `test-code` supplied to `FlagIcon`, expected one of ["af","ax","al","dz","as","ad","ao","ai","aq","ag","ar","am","aw","au","at","az","bs","bh","bd","bb","by","be","bz","bj","bm","bt","bo","bq","ba","bw","bv","br","io","bn","bg","bf","bi","kh","cm","ca","cv","es-ct","ky","cf","td","cl","cn","cx","cc","co","km","cg","cd","ck","cr","ci","hr","cu","cw","cy","cz","dk","dj","dm","do","ec","eg","sv","gq","er","ee","et","eu","fk","fo","fj","fi","fr","gf","pf","tf","ga","gm","ge","de","gh","gi","gr","gl","gd","gp","gu","gt","gg","gn","gw","gy","ht","hm","va","hn","hk","hu","is","in","id","ir","iq","ie","im","il","it","jm","jp","je","jo","kz","ke","ki","kp","kr","kw","kg","la","lv","lb","ls","lr","ly","li","lt","lu","mo","mk","mg","mw","my","mv","ml","mt","mh","mq","mr","mu","yt","mx","fm","md","mc","mn","me","ms","ma","mz","mm","na","nr","np","nl","nc","nz","ni","ne","ng","nu","nf","mp","no","om","pk","pw","ps","pa","pg","py","pe","ph","pn","pl","pt","pr","qa","re","ro","ru","rw","bl","sh","kn","lc","mf","pm","vc","ws","sm","st","sa","sn","rs","sc","sl","sg","sx","sk","si","sb","so","za","gs","ss","es","lk","sd","sr","sj","sz","se","ch","sy","tw","tj","tz","th","tl","tg","tk","to","tt","tn","tr","tm","tc","tv","ug","ua","ae","gb","gb-eng","gb-nir","gb-sct","gb-wls","un","us","um","uy","uz","vu","ve","vn","vg","vi","wf","eh","ye","zm","zw"].
2020-05-04T01:14:32.2383296Z           in FlagIcon
2020-05-04T01:14:32.2383436Z 
2020-05-04T01:14:32.2383565Z        6 |   return (
2020-05-04T01:14:32.2383877Z        7 |     <div className="mb-4 mx-4">
2020-05-04T01:14:32.2384191Z     >  8 |       <FlagIcon className="mx-auto" code={code} size="4x" />
2020-05-04T01:14:32.2384335Z          |       ^
2020-05-04T01:14:32.2384464Z        9 |       {children}
2020-05-04T01:14:32.2384592Z       10 |     </div>
2020-05-04T01:14:32.2384699Z       11 |   )
2020-05-04T01:14:32.2384768Z 
2020-05-04T01:14:32.2385069Z       at printWarning (node_modules/prop-types/checkPropTypes.js:20:15)
2020-05-04T01:14:32.2385389Z       at checkPropTypes (node_modules/prop-types/checkPropTypes.js:82:11)
2020-05-04T01:14:32.2385585Z       at validatePropTypes (node_modules/react/cjs/react.development.js:1714:7)
2020-05-04T01:14:32.2385805Z       at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:1813:5)
2020-05-04T01:14:32.2385995Z       at LanguageItem (src/components/Languages/LanguageItem.tsx:8:7)
2020-05-04T01:14:32.2386504Z       at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:829:32)
2020-05-04T01:14:32.2386797Z       at fn (node_modules/enzyme-adapter-react-16/src/ReactSixteenAdapter.js:645:55)
2020-05-04T01:14:32.2387087Z       at withSetStateAllowed (node_modules/enzyme-adapter-utils/src/Utils.js:99:18)
2020-05-04T01:14:32.2387164Z 
```

**Comment by fabasoad** [comment]
Fixed in _2.0.9_
